apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sdk-apicurio-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sdk-apicurio-registry
    app.kubernetes.io/part-of: apicurio-registry
  name: python-sdk-apicurio-registry
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-sdk-apicurio-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-sdk-apicurio-registry
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sbudhwar-1-tenant/apicurio-registry/python-sdk-apicurio-registry@sha256:ac482aad702c3bfd4830c9b6dfd8ccb88b7920b2c1e04ca51205e3920965ec58
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
